### ISSUE TITLE
pals in same spot on list of other players seem to be sharing stats 0.5.1

### ISSUE THREAD

**Issue by LordNEWNS** [EternalWraith/PalEdit#70] opened 2024-02-02 09:30 UTC
when i open my multiplayer dedicated server file and run the editor and tab through the pals it seems all the pals in the position on the list share the same stats. running on version 0.5.1

|position in list |   player 1 |  player 2  |  player 3  | 
|           1           |   anubis   |  anubis    |   anubis   |
| Matt/Ratt/def | 34/34/67 | 34/34/67 | 34/34/67 |
|           2           |  azurobe  |    arsox    |   anubis   |
| Matt/Ratt/def | 66/86/57 | 66/86/57 | 66/86/57 |
|           3           | beegrade |  bristala   |   anubis   |
| Matt/Ratt/def |  82/50/6  |  82/50/6  |  82/50/6  |

**Comment by KrisCris** [comment] 2024-02-04 17:30
I can confirm this is happening...

**Comment by LordNEWNS** [comment] 2024-02-04 22:02
> I can confirm this is still happening on the latest version 0.5.5. You don't even need the pals to be in the same position on the list... Multiple pals from the same player are sharing the modification.
> 
> [![IMAGE ALT TEXT HERE](https://camo.githubusercontent.com/a7eef72f2c8f1bd10b653fdd89cacd95d9dc878feb7ac1d82b26dcdc08d5e83e/68747470733a2f2f696d672e796f75747562652e636f6d2f76692f597a59542d71664b5631512f302e6a7067)](https://www.youtube.com/watch?v=YzYT-qfKV1Q)

the issue im referring too isn't about passives or modifications. and occurs even before making any changes. 

in the example above for example player ones second slot pal azurobe, and player 2s second slot pal arsox, and player 3s second slot pal anubis, all have 66 mele attack, 86 ranged attack, and 57 defense despite different pals and different levels. this occurred before any modifications of the pals. the pasives were actually all different. so this is a separate issue

**Comment by KrisCris** [comment] 2024-02-07 13:43
Well, after looking into the code... This issue is caused by the way the program saves modified data:

The program tries to save the *displayed data* back to the previously selected pal every time a pal is clicked.

**PalEdit::onselect**:
https://github.com/EternalWraith/PalEdit/blob/f7924cce71d45f5d6bee8fa4ef12b453948d2f1d/PalEdit.py#L323

This is not a perfect implementation, but it works when only one player exists.

---

When you switch to another player, the previously selected pal is not saved, until the next time you click on a pal, i.e. the pal of other players.

**PalEdit::updatestats**
https://github.com/EternalWraith/PalEdit/blob/f7924cce71d45f5d6bee8fa4ef12b453948d2f1d/PalEdit.py#L603

At this moment, `current.get()` returns the currently selected player, not the previous one. So the data of the previously selected pal right before we switch player, is saved to the location of the current one.

---

Here I suggest two potential fixes:

1. Save the data right after a text field is modified. So we are no longer repeatedly saving unchanged data.
2. A quick fix would be:
    - introduce a `targetPlayer` variable
    - use this variable for locating the pal data
    - call updatestats on switching player
    - then update `targetPlayer` to `current.get()`

I could submit an easy fix, but I am still waiting https://github.com/EternalWraith/PalEdit/pull/87 to be merged.

**Comment by taovc** [comment] 2024-02-07 18:05
> Well, after looking into the code... This issue is caused by the way the program updates pal data:
> 
> The program tries to save the _displayed data_ back to the previously selected pal every time a pal is clicked.
> 
> **PalEdit::onselect**:
> 
> https://github.com/EternalWraith/PalEdit/blob/f7924cce71d45f5d6bee8fa4ef12b453948d2f1d/PalEdit.py#L323
> 
> This is not a perfect implementation, but it works when only one player exists.
> 
> When you switch to another player, the previously selected pal is not saved, until the next time you click on a pal, i.e. the pal of other players.
> 
> **PalEdit::updatestats**
> 
> https://github.com/EternalWraith/PalEdit/blob/f7924cce71d45f5d6bee8fa4ef12b453948d2f1d/PalEdit.py#L603
> 
> At this moment, `current.get()` returns the currently selected player, not the previous one. So the data of the previously selected pal, the one from the previously selected player, is saved to the location of the current player.
> 
> Here I suggest two potential fixes:
> 
> 1. Save the data right after a text field is modified. So we are no longer repeatedly saving unchanged data.
> 2. A quick fix would be:
>    
>    * introduce a `targetPlayer` variable
>    * use this variable for locating the pal data
>    * call updatestats on switching player
>    * then update `targetPlayer` to `current.get()`
> 
> I could submit an easy fix, but I am still waiting #87 to be merged.



> Well, after looking into the code... This issue is caused by the way the program updates pal data:
> 
> The program tries to save the _displayed data_ back to the previously selected pal every time a pal is clicked.
> 
> **PalEdit::onselect**:
> 
> https://github.com/EternalWraith/PalEdit/blob/f7924cce71d45f5d6bee8fa4ef12b453948d2f1d/PalEdit.py#L323
> 
> This is not a perfect implementation, but it works when only one player exists.
> 
> When you switch to another player, the previously selected pal is not saved, until the next time you click on a pal, i.e. the pal of other players.
> 
> **PalEdit::updatestats**
> 
> https://github.com/EternalWraith/PalEdit/blob/f7924cce71d45f5d6bee8fa4ef12b453948d2f1d/PalEdit.py#L603
> 
> At this moment, `current.get()` returns the currently selected player, not the previous one. So the data of the previously selected pal, the one from the previously selected player, is saved to the location of the current player.
> 
> Here I suggest two potential fixes:
> 
> 1. Save the data right after a text field is modified. So we are no longer repeatedly saving unchanged data.
> 2. A quick fix would be:
>    
>    * introduce a `targetPlayer` variable
>    * use this variable for locating the pal data
>    * call updatestats on switching player
>    * then update `targetPlayer` to `current.get()`
> 
> I could submit an easy fix, but I am still waiting #87 to be merged.

thanks KrisCris, can you push your fixed code in your repo as a new branch? that's very helpful for me.

**Closed** 2024-02-11 21:40 UTC
